AIRBRIDGE_API_TOKEN = "d20e33a8f985435d98e6b224a8a123ad"
AIRBRIDGE_APP_CODE = "polyball"
AIRBRIDGE_API_TOKEN_NEW = "2dc61bd3e26747d19581397936fca3d5"
AIRBRIDGE_APP_CODE_NEW = "polyballkr"
GITHUB_TOKEN = ""
SECRET_KEY = "polyball_hmac_secret_v1"
